export {default as Home} from './Home'
export {default as Nav } from './Nav'
export {default as Footer } from './Footer'
export {default as SinglePage} from './SinglePage'
export {default as Holdings} from './Holdings'
export {default as LandingCarousel} from './LandingCarousel'
